ServerPort: "8081"
LogConfig:
  Level: "info"
  Format: "console"
  File: "app.log"
  MaxSize: 10
  MaxAge: 7
  Compress: true
  Filename: "app.log"
  ResponseSize: 1000
  ShowConsole: true
MySQL:
  Host: "192.168.1.12"
  Port: 3306
  Username: "sgin"
  Password: "sginZzz@1"
  Database: "sgin"
  ShowSQL: true

MailConfig:
  Host: "smtp.qiye.aliyun.com"
  Port: 465
  Username: "lewis@biggerforum.org"
  Password: ""
  RegisterTile: "AI云助手邮件验证码"

NoRouterFoward: "https://www.baidu.com"
ApiPrefix: "/api"

Upload:
  Dir: "public"